machine:
  image: ubuntu-2004:202111-02
  docker_layer_caching: true
working_directory: ~/kubernetes-monitor
steps:
  - checkout
  - setup_node16
  - install_python_requests
  - run:
      name: Create temporary directory for logs
      command: mkdir -p /tmp/logs/test/integration/openshift3
  - run:
      name: Integration tests OpenShift 3
      command: |
        export IMAGE_TAG_UBI_SUFFIX="-ubi8"
        export KUBERNETES_MONITOR_IMAGE_NAME_AND_TAG=$(./scripts/circleci-jobs/setup-integration-tests.py)
        npm run test:integration:openshift3:yaml
  - run:
      name: Notify Slack on failure
      command: ./scripts/slack/notify_failure.py "${CIRCLE_BRANCH}" "${CIRCLE_JOB}" "${CIRCLE_BUILD_URL}" "${CIRCLE_PULL_REQUEST}" "${SLACK_WEBHOOK}"
      when: on_fail
  - store_artifacts:
      path: /tmp/logs/test/integration/openshift3
